set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/sweethome/vim/bundle/Vundle.vim
call vundle#begin('~/sweethome/vim/bundle')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'altercation/vim-colors-solarized'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
" requires flake8 and pylint to be installed
Plugin 'davidhalter/jedi-vim'
" requires jedi to be installed or fecthed in submodule
Plugin 'rking/ag.vim'
" requires
" aptitude install silversearcher-ag (available since Ubuntu 14.04)
Plugin 'kien/ctrlp.vim'
Plugin 'mattn/emmet-vim'
Plugin 'hynek/vim-python-pep8-indent'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Airline setup
set laststatus=2
set t_Co=256

" solarized 
syntax on
set background=dark
colorscheme solarized

" General
set number
set textwidth=80
set cc=+1

" let tab always be 4 spaces
set shiftwidth=4
set softtabstop=4
set expandtab

" wildmenu
set wildmenu
set wildignore=*.o,*~,*.pyc

" check spelling (requiring aspell, hunspell or ispell to be installed)
set spell

" search
set hlsearch

" Salt state file syntax highlight
filetype on
au BufNewFile,BufRead *.sls set filetype=yaml

" syntastic configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_python_checkers = ['pep8', 'pep257', 'pylint']
let g:syntastic_auto_jump=1

" NerdTree
" Force encoding for NerdTree directorie arrows
set encoding=utf-8
" else directory arrows can be written in ascii
" let g:NERDTreeDirArrows=0

" fix refresh issue on latest vim version with xterm
set ambiwidth=single

"load externalfiles
"execute 'source '. $HOME . '/vim/shortkeys.vim'
map <F2> <Esc>:NERDTreeToggle<CR>
map <F3> <Esc>:CtrlP<CR>
"Toggle for mouse copy/paste
map <F10> <Esc>:set nu textwidth=80 cc=1 nopaste<CR>
map <F12> <Esc>:set nonu textwidth=0 cc=0 paste<CR>
