set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/sweethome/vim/bundle/Vundle.vim
call vundle#begin('~/sweethome/vim/bundle')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'klen/python-mode'
Plugin 'rking/ag.vim'
" require
" aptitude install silversearcher-ag (available since Ubuntu 14.04)
Plugin 'kien/ctrlp.vim'
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
"Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Airline setup
set laststatus=2
set t_Co=256

" General
syntax on
set number
highlight LineNr ctermbg=blue ctermfg=gray
highlight Search ctermfg=DarkBlue
set textwidth=80
set cc=+1

" let tab always be 4 spaces
set shiftwidth=4
set softtabstop=4
set expandtab

" wildmenu
set wildmenu
set wildignore=*.o,*~,*.pyc

" search
set hlsearch

" Salt state file syntax highlight
filetype on
au BufNewFile,BufRead *.sls set filetype=yaml

" python-mode configuration
" python-mode #342 workaround
let g:pymode_rope_lookup_project = 0
" make python-mode sensitive to activated virtualenv
let g:pymode_virtualenv = 1
" trim unused white spaces on save
let g:pymode_trim_whitespaces = 1

"load externalfiles
"execute 'source '. $HOME . '/vim/shortkeys.vim'
map <F2> <Esc>:NERDTreeToggle<CR>
